Updating styles.css for PersonalPortfolio
CCianfloneDev/HTML-CSSProjects pull request #6
Opened 2022-02-06 20:33 UTC by CCianfloneDev

2022-02-06 20:34 UTC, CCianfloneDev commented
Any thoughts @DZ-FSDev ? I find it to be messy, the site however currently looks great, working as intended for smaller devices as well.

2022-02-07 00:57 UTC, DZ-FSDev requested changes
It looks good! I did notice this though:
![image](https://user-images.githubusercontent.com/85122787/152709512-e7d612c7-112f-4812-9747-8c1ee2409ce5.png)

Usually, 320P is the smallest screen you'd want to support.

2022-02-07 01:04 UTC, DZ-FSDev commented
While reviewing at #5, I noticed this too: 

Can be reproduced on:
1. Chrome
2. Brave


![image](https://user-images.githubusercontent.com/85122787/152709876-da0953d5-1161-4a4b-ac5e-a105e5809417.png)

2022-02-07 01:44 UTC, CCianfloneDev commented
Do you have any suggestions on how to go about fixing the weird line breaks? 

I am using: **_word-break: break-all;_** to automatically break the paragraph but it does seem to be iffy.

Should I manually make line breaks using the **< br >** element? Or might you know a better way?

2022-02-08 14:02 UTC, DZ-FSDev requested changes

2022-02-08 14:02 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
> +	word-break: break-all;
- [ ] The `word-break` attribute set to `break-all` is the culprit. It tells the browser to break at any character of a word that overflows the container width. I'd remove it.
- [ ] Use  `word-wrap: break-word;` instead as you want to break each word as a unit.
> `word-break: break-all;` - Breaks per character
> `word-wrap: break-word;` - Breaks per word

2022-02-08 19:56 UTC, DZ-FSDev requested changes
Try to stick to a general set of styles that can be applied to all pages. If you need to have separate styles that use a base CSS, explore the option of having multiple CSS files with the sub-stylesheets containing `@import url("base.css");`

2022-02-08 19:56 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
>  	flex: 1;
- [ ] `nav ul` is not a flex-parent. Is this `flex: 1;` required?

2022-02-08 19:56 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
> +
- [ ] Would `width: 100%` achieve similar?

2022-02-08 19:56 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
> +/***********CSS SEPERATE FOR CONTACT PAGE BELOW***********/
?

2022-02-08 19:56 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
> +/***********CSS SEPERATE FOR PROJECTS PAGE BELOW***********/
?

2022-02-08 19:56 UTC, DZ-FSDev commented on PersonalPortfolio/styles.css
> +/*Poisitioning for construction photo*/
- [ ] Positioning.

2022-02-09 00:23 UTC, CCianfloneDev commented on PersonalPortfolio/styles.css
> +
Sadly nope, I just tested it, only the text area is clickable, I want it so that you can click the entire li element to open the link.

2022-02-09 00:25 UTC, CCianfloneDev commented on PersonalPortfolio/styles.css
>  	flex: 1;
When I remove it, it looks like this: 
![image](https://user-images.githubusercontent.com/24930067/153098488-08a3d6ef-5a57-4a09-987b-e5128ef0caac.png)

2022-02-10 16:47 UTC, closed without merging